// Map database. Only one real map exists today (the procedural abbey, always
// generated by src/mapgen.js regardless of selection — map choice has no gameplay
// effect yet). Locked entries are UI-only placeholders so the select screen reads
// as "more maps coming" rather than hiding the feature. Unlock a map for real by
// flipping `locked: false` and adding actual mapgen support if it needs its own logic.
export const MAPS = [
  { id: 'abbey', name: 'Abbaye', desc: 'Cloître en ruine, la nuit.', locked: false },
  { id: 'soon_1', name: '???', desc: 'Bientôt disponible', locked: true },
  { id: 'soon_2', name: '???', desc: 'Bientôt disponible', locked: true },
];

export const DEFAULT_MAP_ID = 'abbey';
