export const state = {
  enemies: [],
  bullets: [],
  xpOrbs: [],
  puddles: [],
  tunasDrops: [],
  tunasEarnedThisRun: 0,
  killCount: 0,
  gameTime: 0,
  paused: false,
  gameOver: false,
  started: false,
  spawnTimer: 0,
  godmode: false,
  pendingLevelUps: 0,
};
